version: '3'
services:  
  postgres:
    image: postgres
    container_name: postgres
    command: postgres -c 'max_connections=250'
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=employees
    volumes:
      - ./data/postgres_data:/var/lib/postgresql
    ports:
      - 5455:5432
    networks:
      - psql-pgql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com  
      - PGADMIN_DEFAULT_PASSWORD=admin         
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin       
    ports:
      - 5050:80                               
    depends_on:
      - postgres
    networks:
      - psql-pgql
networks:
  psql-pgql: